# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  RestoreProjects: 'HomeMaintenanceNotification.csproj'

steps:
- task: UseDotNet@2
  displayName: Use .NET Core SDK 8
  inputs:
    packageType: 'sdk'
    version: '8.x'

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: $(RestoreProjects)

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: $(RestoreProjects)
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayname: Publish
  inputs:
    targetPath: '$build.artifactstagingdirectory'
    artifactName: drop
  condition: succeeded()

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    artifactName: 'drop'
    targetPath: $(Pipeline.workspace)


- task: AzureFunctionApp@1
  displayName: DeployFunction
  inputs:
    azureSubscription: $(serviceConnection)
    appType: 'functionapp'
    appName: $(functionName)
    deployToSlotOrASE: true
    resourceGroupName: $(resourceGroup)
    slotName: 'production'
    package: '$(Pipeline.workspace)/HomeMaintenanceNotification.zip'
    AppSettings: >-
     -ASPNET_ENVIRONMENT "Production"
    deploymentMethod: 'auto'
  