# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master
- azure-pipelines

pool:
  name: TangFamilySelfHosted

variables:
  group: HomeMaintenance
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  RestoreProjects: 'HomeMaintenanceNotification.csproj'

steps:
#- task: UseDotNet@2
#  displayName: Use .NET Core SDK 6
#  inputs:
#    packageType: 'sdk'
#    version: '6.x'

#- task: DotNetCoreCLI@2
#  displayName: Restore
#  inputs:
#    command: restore
#    projects: $(RestoreProjects)
- script: |
    dotnet restore
    dotnet build --configuration Release

#- task: DotNetCoreCLI@2
#  displayName: Build
#  inputs:
#    command: build
#    projects: $(RestoreProjects)
#    arguments: '--configuration $(buildConfiguration)'

#- task: DotNetCoreCLI@2
#  displayName: Publish
#  inputs:
#    targetPath: '$build.artifactstagingdirectory'
#    artifactName: drop
#    condition: succeeded()

#- task: DownloadPipelineArtifact@2
#  inputs:
#    buildType: 'current'
#    artifactName: 'drop'
#    targetPath: $(Pipeline.workspace)

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--configuration Release --output publish_output'
    projects: '*.csproj'
    publishWebProjects: false
    modifyOutputPath: false
    zipAfterPublish: false
- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
    artifactName: 'drop'

- task: AzureFunctionApp@1
  displayName: DeployFunction
  inputs:
    azureSubscription: 'AzureDevOpsToAzure'
    appType: 'functionapp'
    appName: $(functionName)
    deployToSlotOrASE: true
    resourceGroupName: $(resourceGroup)
    slotName: 'production'
    package: '$(Pipeline.workspace)/HomeMaintenanceNotification.zip'
    AppSettings: >-
      -ASPNET_ENVIRONMENT "Production"
      deploymentMethod: 'auto'
  